namespace CxComponent.StaticLibrary2
{
    [default_interface]
    unsealed runtimeclass Class2
    {
        Class2();
        Int32 MyProperty;
        overridable void SetProperty(Int32 value);
    }
}
